### ISSUE TITLE
vue版本与 vue-template-compiler不一致报错

### ISSUE THREAD

**Issue by LindsyT** [ChuHoMan/vue-demi-component-template#10]
**node版本**
v16.17.0
**vue-cli版本**
@vue/cli 4.5.13

>pnpm install 成功
>pnpm run dev:2 报错

`PS E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main> pnpm run dev:2

> vue-demi-template-component@1.0.0 dev:2 E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main
> vue-demi-switch 2 vue2 && pnpm --filter vue2-playground dev

[vue-demi] Switched for Vue 2 (entry: "vue2")

> vue2-playground@1.0.0 dev E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main\vue2-playground
> vite

failed to load config from E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main\vue2-playground\vite.config.ts
error when starting dev server:
Error:

Vue packages version mismatch:

- vue@3.2.47 (E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main\node_modules\.pnpm\vue@3.2.47\node_modules\vue\index.js)
- vue-template-compiler@2.6.14 (E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main\node_modules\.pnpm\vue-template-compiler@2.6.14\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object._require.extensions.<computed> [as .js] (file:///E:/OTHER/OTHER%20FRAMEWORK/vue-demi-component-template-main/node_modules/.pnpm/vite@4.3.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64527:17)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main\node_modules\.pnpm\vite-plugin-vue2@2.0.3_vite@4.3.9_vue-template-compiler@2.6.14\node_modules\vite-plugin-vue2\dist\utils\descriptorCache.js:34:42)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object._require.extensions.<computed> [as .js] (file:///E:/OTHER/OTHER%20FRAMEWORK/vue-demi-component-template-main/node_modules/.pnpm/vite@4.3.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64527:17)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
E:\OTHER\OTHER FRAMEWORK\vue-demi-component-template-main\vue2-playground:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  vue2-playground@1.0.0 dev: `vite`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by ChuHoMan** [comment]
尝试先 `pnpm i` 后再使用 `pnpm run dev:2`。
Try `pnpm i` followed by `pnpm run dev:2`.
